/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package student.grade.calculator;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class EnterMarks extends javax.swing.JFrame {

    /**
     * Creates new form EnterMarks
     */
    public static String subject1 = EnterSubjects.subject1;
    public static String subject2 = EnterSubjects.subject2;
    public static String subject3 = EnterSubjects.subject3;
    public static String subject4 = EnterSubjects.subject4;
    public static String subject5 = EnterSubjects.subject5;
    public static String subject6 = EnterSubjects.subject6;

    public static float marks1;
    public static float marks2;
    public static float marks3;
    public static float marks4;
    public static float marks5;
    public static float marks6;

    public static float totalMarks;
     public static float averagePercentage;
    public static char grade;
    public static String result;
    public EnterMarks() {

        initComponents();

        sub1Label.setText(subject1 + " :");
        sub2Label.setText(subject2 + " :");
        sub3Label.setText(subject3 + " :");
        sub4Label.setText(subject4 + " :");
        sub5Label.setText(subject5 + " :");
        sub6Label.setText(subject6 + " :");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        marksPanel = new javax.swing.JPanel();
        sub1marks = new javax.swing.JTextField();
        sub2marks = new javax.swing.JTextField();
        sub3marks = new javax.swing.JTextField();
        sub4marks = new javax.swing.JTextField();
        sub5marks = new javax.swing.JTextField();
        sub6marks = new javax.swing.JTextField();
        sub1Label = new javax.swing.JLabel();
        sub2Label = new javax.swing.JLabel();
        sub3Label = new javax.swing.JLabel();
        sub4Label = new javax.swing.JLabel();
        sub5Label = new javax.swing.JLabel();
        sub6Label = new javax.swing.JLabel();
        resultBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Enter Marks(Out Of 100)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        marksPanel.setBackground(new java.awt.Color(204, 255, 204));

        sub1marks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub2marks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub3marks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub4marks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub5marks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub6marks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        sub1Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sub1Label.setText("Subject 1 :");

        sub2Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sub2Label.setText("Subject 2 :");

        sub3Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sub3Label.setText("Subject 3 :");

        sub4Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sub4Label.setText("Subject 4 :");

        sub5Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sub5Label.setText("Subject 5 :");

        sub6Label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sub6Label.setText("Subejct 6 :");

        javax.swing.GroupLayout marksPanelLayout = new javax.swing.GroupLayout(marksPanel);
        marksPanel.setLayout(marksPanelLayout);
        marksPanelLayout.setHorizontalGroup(
            marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, marksPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sub2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sub3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(marksPanelLayout.createSequentialGroup()
                        .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sub4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sub6Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sub5Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(sub1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sub5marks, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(sub4marks)
                    .addComponent(sub3marks)
                    .addComponent(sub2marks)
                    .addComponent(sub1marks)
                    .addComponent(sub6marks))
                .addContainerGap())
        );
        marksPanelLayout.setVerticalGroup(
            marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marksPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(marksPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(sub1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 19, Short.MAX_VALUE))
                    .addComponent(sub1marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub2marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub3marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub3Label))
                .addGap(18, 18, 18)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub4marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub4Label))
                .addGap(18, 18, 18)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub5marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub5Label))
                .addGap(18, 18, 18)
                .addGroup(marksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sub6marks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sub6Label))
                .addGap(45, 45, 45))
        );

        resultBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        resultBtn.setText("Display Result");
        resultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(resultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(179, 179, 179)
                    .addComponent(marksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(373, Short.MAX_VALUE)
                .addComponent(resultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(marksPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(106, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBtnActionPerformed
        // TODO add your handling code here:

        marks1 = Float.parseFloat(sub1marks.getText().toString());
        marks2 = Float.parseFloat(sub2marks.getText().toString());
        marks3 = Float.parseFloat(sub3marks.getText().toString());
        marks4 = Float.parseFloat(sub4marks.getText().toString());
        marks5 = Float.parseFloat(sub5marks.getText().toString());
        marks6 = Float.parseFloat(sub6marks.getText().toString());

        totalMarks = marks1 + marks2 + marks3 + marks4 + marks5 + marks6;

        averagePercentage=(totalMarks/600)*100;
        
        if(averagePercentage >= 80){
            grade='A';
            
        }
        else if(averagePercentage>=60 && averagePercentage < 80){
            
            grade='B';
        }
        else if(averagePercentage>=40 && averagePercentage<60){
            grade='C';
        }
        else{
            grade='D';
            
        }
        
        result="Total Marks Obtained = "+totalMarks+
                "\nAverage Percentage of student = "+averagePercentage+
                "\nGrade Obtained by student = "+grade;
        
        
        JOptionPane.showMessageDialog(this, result);
        
        
    }//GEN-LAST:event_resultBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterMarks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterMarks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel marksPanel;
    private javax.swing.JButton resultBtn;
    public static javax.swing.JLabel sub1Label;
    public static javax.swing.JTextField sub1marks;
    public static javax.swing.JLabel sub2Label;
    public static javax.swing.JTextField sub2marks;
    public static javax.swing.JLabel sub3Label;
    public static javax.swing.JTextField sub3marks;
    public static javax.swing.JLabel sub4Label;
    public static javax.swing.JTextField sub4marks;
    public static javax.swing.JLabel sub5Label;
    public static javax.swing.JTextField sub5marks;
    public static javax.swing.JLabel sub6Label;
    public static javax.swing.JTextField sub6marks;
    // End of variables declaration//GEN-END:variables
}
